---
title: "A la recherche de normes dans les champs taxonomiques dans les BD"
author: "Olivier Leroy"
date: "1/7/2021"
output: html_document
---

# Botanique 

Ici je ne vais prendre que les descriptions du nom des arbres. Les aspects architecture, age, stade de developement etc seront abordés plus loin. 

## Nomenclature botanique 

Un patron fréquent dans les bases de données des arbres est la séparation genre / espèce en deux colonnes (voir plus si on a un nom en trois ou quatres mots) . On a une colonne avec le nom de genre et une seconde avec un epithète. Ainsi *Quercus robur* est du genre *Quercus* et son epithète est *robur*. Cette forme composée en deux mots est recommandée par l'[ICN](https://en.wikipedia.org/wiki/International_Code_of_Nomenclature_for_algae,_fungi,_and_plants). On peut constater que le non de genre à sa première lettre capitalisée ce qui n'est pas le cas de l'epithète. Enfin cette régle est une convention il existe d'autre standarts (prendre un exemple avec le nom du descripteur?). 

Il existe des divisions en dessous de l'éspèce (sous espèce, varitée, cultivar etc..). Dans ce cas on va passer à une nomenclature dîte en trois noms. Il faut alors reprendre les deux premiers mots y ajouter le type (var. pour varité par exemple) et donner ce nom de type. Ainsi on peut avoir *Quercus ilex* subsp. *rotundifolia* pour la sous espèce de chêne vert à glands dit tendres. Il faut noter que les concensus au niveau des sous espèces sont moins fréquents chez les botanistes. 

Il y a cependant des écarts à cette régle (des autres régles plus specifiques exactement) ainsi quand un algorithme  prend le premier nom pour genre  puis le second pour celui de l'epithète il va parfois prendre autre chose et ainsi de suite. 

Voici une liste, probablement non exhaustive, concernant les problèmes que j'ai rencontré dans ces bases de données et des propositions de solutions. 

## Liste de problèmes et de début de solution

### La coquille 

Ici pas beaucoup d'idée : regarder comment les moteurs de recherche font ?

### TOUS CAPITALISE (ou pas de capitalisation)

Ici je propose de passer par une fonction qui passe tous en miniscule, capitalise la première lettre et retire les *white space*. Au passage on note que les "espaces blancs" peuvent être un problème en soit. 

Voici ma première version: 

```{r first_maj}
first_maj <- function(une_liste_de_nom){                        # prend une liste de nom ou un vecteur
    une_liste_de_nom <- trimwc(tolower(une_liste_de_nom))       # enlève les ws et ninore tous 
    paste0(toupper(substr(une_liste_de_nom, 1, 1)),             # capitalise la première lettre 
           substr(une_liste_de_nom, 2, nchar(une_liste_de_nom)) # et la colle au reste decapitalisé
           ) 
    }
```

### "NANA", "NA NA",  Na, etc ..

Ce sont des valeurs nulles transformées en chaine de caractères. On retrouve ainsi dans des bases des "NANA" (ou "NA NA") : probalement un arbre inconnu qui est "NA" dans le champs genre et "NA" dans l'epithète.  Une concatenation malheureuse nous l'a transformé. (NB nous n'avons pas toujours deux champs genre et espèce mais parfois juste un). 

Ici je pense mettre en place des expressions regulières (à voir à quel niveau, sur quel programme, etc ..)
