#### chargement des fichiers
library(sf)

paris <- st_read("sources/les-arbres.geojson")
lyon <- st_read("sources/abr_arbres_alignement.abrarbre.shp")
bordeau <- st_read("sources/bor_arbres.geojson")
nice <- st_read("sources/ev-arbre-opendata-2019.geojson")
grenoble <- st_read("sources/ARBRES_TERRITOIRE_VDG_EPSG4326.json")
montpellier <- st_read("sources/MMM_MTP_ArbresAlign.shp")
grand_paris_seine_ouest <- st_read("sources/arbres-v2.json")
agen <- st_read("sources/arbres.shp")
saint_quentinois <- st_read("sources/ARBRES.shp")
metz <- st_read("sources/vrd_esv_arb.shp")
seine_saint_denis <- st_read("sources/fr-dpt93-1646.json")
versailles <- st_read("sources/VER_Espaces_verts.json")
nevers <- st_read("sources/ARBRE_ALIGNEMENT.shp")
Toulouse <- st_read("sources/arbres-d-alignement.shp")
orleans <- st_read("sources/espace_publicev_arbres.shp")
saint_egreve <- st_read("sources/Arbres_Saint_Egreve.shp")
bayonne <- st_read("sources/ev_arbres.json")
issy <- st_read("sources/arbres-dalignement-sur-la-voirie-departementale.shp")
rennes1 <- st_read("sources/gev_aorn.json")
rennes2 <- st_read("sources/gev_aali.json")
mulhouse <- st_read("sources/68224_arbres_alignement.json")
divonne_les_bains_fr <- st_read("sources/arbre_p_r84.json")
bretagne_berge <- st_read("sources/patrimoine-arbore-ponctuel-des-voies-navigables-appartenant-a-la-region-bretagne.shp")
guigamp <- st_read("sources/Arbres de la Ville de Guingamp.csv")
guigamp <- st_as_sf(guigamp, coords = c("longitude", "latitude"), crs = 4326)
paris_sud <- st_read("sources/patrimoine-arbore.json")
haut_de_seine <-st_read("sources/cadastre-vert-les-arbres.json")
pau <- st_read("sources/gev_AALI_WGS84.shp")
haut_de_seine <-st_read("sources/cadastre-vert-les-arbres.json")
nevers2 <- st_read("sources/ARBRES_ORNEMENTS.shp")
iau_ecoline <- st_read("sources/elements-fixes-ponctuels-de-la-couche-ecoline-dile-de-france.json")
iau_ecoline <- iau_ecoline[iau_ecoline$ele_txt == "Arbre isolé",]

liste_data <- mget(ls())
