#### chargement des fichiers
library(sf)

paris <- st_read("sources/les-arbres.geojson")
lyon <- st_read("sources/abr_arbres_alignement.abrarbre.shp")
bordeaux <- st_read("sources/bor_arbres.geojson")
nice <- st_read("sources/ev-arbre-opendata-2019.geojson")
grenoble <- st_read("sources/ARBRES_TERRITOIRE_VDG_EPSG4326.json")
montpellier <- st_read("sources/MMM_MTP_ArbresAlign.shp")
grand_paris_seine_ouest <- st_read("sources/arbres-v2.geojson")
agen <- st_read("sources/arbres.shp")
saint_quentinois <- st_read("sources/ARBRES.shp")
metz <- sf::st_read("sources/vrd_esv_arb.shp")
metz_arbres_rq <- sf::st_read("sources/metz_arbres_rq.json")
seine_saint_denis <- st_read("sources/fr-dpt93-1646.json")
versailles <- st_read("sources/VER_Espaces_verts.json")
nevers <- st_read("sources/ARBRE_ALIGNEMENT.shp")
Toulouse <- st_read("sources/arbres-d-alignement.shp")
orleans <- st_read("sources/espace_publicev_arbres.shp")
saint_egreve <- st_read("sources/Arbres_Saint_Egreve.shp")
bayonne <- st_read("sources/ev_arbres.json")
issy <- st_read("sources/arbres-dalignement-sur-la-voirie-departementale.shp")
rennes1 <- st_read("sources/gev_aorn.json")
rennes2 <- st_read("sources/gev_aali.json")
mulhouse <- st_read("sources/68224_arbres_alignement.json")
divonne_les_bains_fr <- st_read("sources/arbre_p_r84.json")
bretagne_berge <- st_read("sources/patrimoine-arbore-ponctuel-des-voies-navigables-appartenant-a-la-region-bretagne.shp")
guigamp <- st_read("sources/Arbres de la Ville de Guingamp.csv")
guigamp <- st_as_sf(guigamp, coords = c("longitude", "latitude"), crs = 4326)
paris_sud <- st_read("sources/patrimoine-arbore.json")
haut_de_seine <-st_read("sources/cadastre-vert-les-arbres.json")
pau_ali <- st_read("sources/gev_AALI_WGS84.shp")
nevers2 <- st_read("sources/ARBRES_ORNEMENTS.shp")
iau_ecoline <- st_read("sources/elements-fixes-ponctuels-de-la-couche-ecoline-dile-de-france.json")
iau_ecoline <- iau_ecoline[iau_ecoline$ele_txt == "Arbre isolé",]
argenteuil <- st_read("sources/Les_arbres_de_l_espace_public.geojson")
limousin_arbres_rq <- st_read("sources/drive-download-20210416T150023Z-001/l_arbres_r74.json") 
bourgogne_arbres_rq <- st_read("sources/bourgogne_arbre_rq.geojson")
idf_arbres_rq <- sf::st_read("sources/arbres-remarquablesidf.geojson")
saint_dizier <- st_read("sources/CA-SAINT-DIZIER-ARBRES_2019.json")
versailles_parc <- st_read("sources/arbres-dans-les-parcs-de-la-ville-de-versailles.geojson")
rouen_arbers_rq <- sf::st_read("sources/arbres_MRN.shp")
pnr_verdon_ali <- sf::st_read("sources/pnrv_20170727_alignements_arbres_2014_2015.shp")
pnr_verdon_iso <- sf::st_read("sources/pnrv_20170727_arbres_isoles.shp")
bas_rhin_arbres_rq <- sf::st_read("sources/CD67_ENVIRONNEMENT_ARBRES_REMARQUABLES_JUIN_2019.json")
#PACA_ali_rq <- sf::st_read("sources/DPA_AARem.json")
bretagne_maec <- sf::st_read("sources/maec_2020_point.json")
haut_de_seine_rq <- sf::st_read("sources/arbres-remarquables.geojson")
#montpellier_arbres_rq <- sf::st_read("sources/VilleMTP_MTP_ArbresRemarq.geojson")
pau_orn <- sf::st_read("sources/gev_AORN_RGF93.shp")

liste_data <- mget(ls())
